/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInterfacePARKUM.java
 *
 * Created on 27/Dez/2010, 18:58:25
 */

package swing;

import baseDados.Model;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Hugo
 */
public class JInterfacePARKUM extends javax.swing.JFrame {
    ResultSet rSet = null;
    /** Creates new form JInterfacePARKUM */
    public JInterfacePARKUM() {
        //Util.centerOnScreen(this);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClientesRegistados = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jLabelProcura1 = new javax.swing.JLabel();
        jLabelProcura2 = new javax.swing.JLabel();
        jTextFieldProcurar = new javax.swing.JTextField();
        jButtonProcurar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jRadioButtonNCliente = new javax.swing.JRadioButton();
        jRadioButtonNomeCliente = new javax.swing.JRadioButton();
        jButtonRegistarCliente = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabelNumerroCliente = new javax.swing.JLabel();
        jLabelALTnCliente = new javax.swing.JLabel();
        jLabelALTnomeCliente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabelModoEntrada = new javax.swing.JLabel();
        jLabelALTmodoEntrada = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelALTmatricVeic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jALTnib = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButtonRelClienteGerarRel = new javax.swing.JButton();
        jRadioButtonRelClienteNentrada = new javax.swing.JRadioButton();
        jRadioButtonRelClienteTemposEstacion = new javax.swing.JRadioButton();
        jRadioButtonRelClienteValorMensal = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPagamentosAtrasoCliente = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPagamentosAtraso = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jButtonRelDiaGerar = new javax.swing.JButton();
        jRadioButtonRelDiaTotalEntSai = new javax.swing.JRadioButton();
        jRadioButtonRelDiaOcupaNivel = new javax.swing.JRadioButton();
        jRadioButtonRelDiaTempoEsta = new javax.swing.JRadioButton();
        jRadioButtonRelDiaEntEst = new javax.swing.JRadioButton();
        jRadioButtonRelDiaTemposPag = new javax.swing.JRadioButton();
        jRadioButtonRelDiaNBilhete = new javax.swing.JRadioButton();
        jRadioButtonRelDiaViaturas = new javax.swing.JRadioButton();
        jLabelRelDia1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButtonRelMPGerar = new javax.swing.JButton();
        jRadioButtonRelMPNpag = new javax.swing.JRadioButton();
        jRadioButtonRelMPTotal = new javax.swing.JRadioButton();
        jRadioButtonRelMPNumPerce = new javax.swing.JRadioButton();
        jRadioButtonRelMPAvarias = new javax.swing.JRadioButton();
        jLabelRelMP1 = new javax.swing.JLabel();
        jTextFieldRelMPIdMaq = new javax.swing.JTextField();
        jLabelRelMP2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButtonRelFacGerar = new javax.swing.JButton();
        jRadioButtonRelFacPagDin = new javax.swing.JRadioButton();
        jRadioButtonRelFacpagCartao = new javax.swing.JRadioButton();
        jRadioButtonRelFacPagCheque = new javax.swing.JRadioButton();
        jLabelRelFac1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButtonTabDistGera = new javax.swing.JButton();
        jComboBoxTabDistHora = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabelTabDist1 = new javax.swing.JLabel();
        jLabelTabDist2 = new javax.swing.JLabel();
        jComboBoxTabDistNivel = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneManDescri = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldManNumMaq = new javax.swing.JTextField();
        jButtonManRegista = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldManTempo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNotificacoes = new javax.swing.JList();
        jLabelIniciarSessão = new javax.swing.JLabel();
        jLabelUserLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListClientesRegistados.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Registados"));
        try {
            rSet = baseDados.Query.queryClientes();
            DefaultListModel model = new DefaultListModel();
            while (rSet.next())
            model.addElement(rSet.getString(1));
            jListClientesRegistados.setModel(model);
        }
        catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }
        jScrollPane2.setViewportView(jListClientesRegistados);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Procura de Clientes"));

        jLabelProcura1.setText("A Procura será feita de acordo com o modo de ");

        jLabelProcura2.setText("visualização em que está!");

        jTextFieldProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProcurarActionPerformed(evt);
            }
        });

        jButtonProcurar.setText("Procurar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProcura1)
                    .addComponent(jLabelProcura2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonProcurar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabelProcura1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProcura2)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProcurar)
                    .addComponent(jTextFieldProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Visualização"));

        jRadioButtonNCliente.setText("Nº de Cliente");
        jRadioButtonNCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNClienteActionPerformed(evt);
            }
        });

        jRadioButtonNomeCliente.setText("Nome do Cliente");
        jRadioButtonNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonNCliente)
                    .addComponent(jRadioButtonNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jRadioButtonNCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNomeCliente))
        );

        jButtonRegistarCliente.setText("Registar Novo Cliente");

        jButtonEditar.setText("Editar Cliente");

        jButtonRemover.setText("Remover Cliente");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os Clientes" }));

        jLabelNumerroCliente.setText("Número do Cliente");

        jLabelALTnCliente.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelALTnCliente.setText("nCliente");

        jLabelALTnomeCliente.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelALTnomeCliente.setText("nomeCliente");

        jLabelNomeCliente.setText("Nome do Cliente");

        jLabelModoEntrada.setText("Modo de Entrada");

        jLabelALTmodoEntrada.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelALTmodoEntrada.setText("modoEntrada");

        jLabelMatricula.setText("Matricula do Veiculo");

        jLabelALTmatricVeic.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelALTmatricVeic.setText("matricVeic");

        jLabel1.setText("NIB");

        jALTnib.setFont(new java.awt.Font("Tahoma", 1, 11));
        jALTnib.setText("nib");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumerroCliente)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jALTnib)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelALTnCliente)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula)
                            .addComponent(jLabelModoEntrada))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelALTmodoEntrada)
                            .addComponent(jLabelALTmatricVeic)))
                    .addComponent(jLabelALTnomeCliente))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelALTnCliente)
                    .addComponent(jLabelNumerroCliente)
                    .addComponent(jLabelModoEntrada)
                    .addComponent(jLabelALTmodoEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jLabelALTnomeCliente)
                    .addComponent(jLabelMatricula)
                    .addComponent(jLabelALTmatricVeic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jALTnib))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Informações do Cliente", jPanel7);

        jButtonRelClienteGerarRel.setText("Gerar Relatório");

        jRadioButtonRelClienteNentrada.setText("Nº de entradas");

        jRadioButtonRelClienteTemposEstacion.setText("Tempos médios de estacionamento");

        jRadioButtonRelClienteValorMensal.setText("Valor Mensal a Facturar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jRadioButtonRelClienteNentrada)
                        .addGap(60, 60, 60)
                        .addComponent(jRadioButtonRelClienteTemposEstacion))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jRadioButtonRelClienteValorMensal)
                        .addGap(220, 220, 220)
                        .addComponent(jButtonRelClienteGerarRel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRelClienteNentrada)
                    .addComponent(jRadioButtonRelClienteTemposEstacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRelClienteValorMensal)
                    .addComponent(jButtonRelClienteGerarRel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Relatórios sobre o Cliente", jPanel13);

        jScrollPane4.setViewportView(jListPagamentosAtrasoCliente);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Lista de Pagamentos em Atraso do Cliente", jPanel14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jButtonRegistarCliente)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonRemover)
                            .addComponent(jButtonRegistarCliente)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestão de Clientes", jPanel3);

        jScrollPane5.setViewportView(jListPagamentosAtraso);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listagem de Pagamentos em Atraso", jPanel15);

        jButtonRelDiaGerar.setText("Gerar Relatório");

        jRadioButtonRelDiaTotalEntSai.setText("Total de entradas e saidas");
        jRadioButtonRelDiaTotalEntSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTotalEntSaiActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaOcupaNivel.setText("Ocupações por Nível");
        jRadioButtonRelDiaOcupaNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaOcupaNivelActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaTempoEsta.setText("Tempos de Estacionamento");
        jRadioButtonRelDiaTempoEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTempoEstaActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaEntEst.setText("Tempos entre a entrada e estacionamento, por nível");
        jRadioButtonRelDiaEntEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaEntEstActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaTemposPag.setText("Tempos entre pagamento do bilhete de parque e efectiva saída");
        jRadioButtonRelDiaTemposPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTemposPagActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaNBilhete.setText("Número de Bilhetes Estraviados");
        jRadioButtonRelDiaNBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaNBilheteActionPerformed(evt);
            }
        });

        jRadioButtonRelDiaViaturas.setText("Viaturas que não entraram nem sairam (Relativamente aos clientes registados)");
        jRadioButtonRelDiaViaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaViaturasActionPerformed(evt);
            }
        });

        jLabelRelDia1.setText("Selecione o tipo de relatório que pretende obter:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonRelDiaOcupaNivel)
                        .addComponent(jRadioButtonRelDiaTempoEsta)
                        .addComponent(jRadioButtonRelDiaEntEst)
                        .addComponent(jRadioButtonRelDiaNBilhete)
                        .addComponent(jRadioButtonRelDiaViaturas)
                        .addComponent(jRadioButtonRelDiaTotalEntSai)
                        .addComponent(jRadioButtonRelDiaTemposPag))
                    .addComponent(jLabelRelDia1))
                .addGap(122, 122, 122)
                .addComponent(jButtonRelDiaGerar)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jButtonRelDiaGerar)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelDia1)
                .addGap(5, 5, 5)
                .addComponent(jRadioButtonRelDiaTotalEntSai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaOcupaNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaTempoEsta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaEntEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaTemposPag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaNBilhete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelDiaViaturas)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Relatórios Diários", jPanel9);

        jButtonRelMPGerar.setText("Gerar Relatório");

        jRadioButtonRelMPNpag.setText("Número de Pagamentos por tipo");
        jRadioButtonRelMPNpag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPNpagActionPerformed(evt);
            }
        });

        jRadioButtonRelMPTotal.setText("Total recebido por cada tipo de pagamento(Dinheiro ou Cartão Magnético)");
        jRadioButtonRelMPTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPTotalActionPerformed(evt);
            }
        });

        jRadioButtonRelMPNumPerce.setText("Número e percegem de recibos emitido e o seu total");
        jRadioButtonRelMPNumPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPNumPerceActionPerformed(evt);
            }
        });

        jRadioButtonRelMPAvarias.setText("Número de Avarias e operações de manutenção registadas");
        jRadioButtonRelMPAvarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPAvariasActionPerformed(evt);
            }
        });

        jLabelRelMP1.setText("Insira o nº de indentificação da máquina que pretende obter o relatório:");

        jLabelRelMP2.setText("Selecione o tipo de relatório que pretende obter:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonRelMPNpag)
                        .addComponent(jRadioButtonRelMPTotal)
                        .addComponent(jRadioButtonRelMPAvarias)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                            .addComponent(jRadioButtonRelMPNumPerce)
                            .addGap(108, 108, 108)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabelRelMP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRelMPIdMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelRelMP2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addComponent(jButtonRelMPGerar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRelMP1)
                    .addComponent(jTextFieldRelMPIdMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabelRelMP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelMPNpag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelMPTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelMPNumPerce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonRelMPAvarias)
                .addGap(21, 21, 21)
                .addComponent(jButtonRelMPGerar)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Relatórios Máquinas de Pagamento", jPanel10);

        jButtonRelFacGerar.setText("Gerar Relatório");

        jRadioButtonRelFacPagDin.setText("Facturanção de pagamentos com dinheiro");
        jRadioButtonRelFacPagDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacPagDinActionPerformed(evt);
            }
        });

        jRadioButtonRelFacpagCartao.setText("Facturação de pagamentos com cartão magnético");
        jRadioButtonRelFacpagCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacpagCartaoActionPerformed(evt);
            }
        });

        jRadioButtonRelFacPagCheque.setText("Facturação de pagamentos com cheque");
        jRadioButtonRelFacPagCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacPagChequeActionPerformed(evt);
            }
        });

        jLabelRelFac1.setText("Selecione o tipo de relatório que pretende obter:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addComponent(jButtonRelFacGerar)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonRelFacPagDin)
                    .addComponent(jRadioButtonRelFacPagCheque)
                    .addComponent(jRadioButtonRelFacpagCartao))
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelFac1)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabelRelFac1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonRelFacPagDin)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonRelFacpagCartao)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonRelFacPagCheque)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelFacGerar)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Relatórios de Facturação", jPanel12);

        jButtonTabDistGera.setText("Gerar Relatório");

        jComboBoxTabDistHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel12.setText("h");

        jLabelTabDist1.setText("Escolha o nível que pretende opter relatório:");

        jLabelTabDist2.setText("Escolha a hora do dia de que pretende obter o relatório");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addComponent(jButtonTabDistGera)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTabDist2)
                    .addComponent(jLabelTabDist1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTabDistNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTabDistHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTabDist1)
                    .addComponent(jComboBoxTabDistNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTabDist2)
                    .addComponent(jComboBoxTabDistHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(54, 54, 54)
                .addComponent(jButtonTabDistGera)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tabela Distribuição de Ocupações", jPanel11);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatórios", jPanel4);

        jTextPaneManDescri.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição da Manutenção"));
        jScrollPane3.setViewportView(jTextPaneManDescri);

        jLabel15.setText("Preencha os campos que se seguem para regitar a manutenção");

        jLabel16.setText("Número da Máquina:");

        jButtonManRegista.setText("Registar Manutenção");
        jButtonManRegista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManRegistaActionPerformed(evt);
            }
        });

        jLabel17.setText("Tempo Gasto (em minutos):");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                            .addComponent(jButtonManRegista, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldManNumMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldManTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldManNumMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldManTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonManRegista)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manutenção", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Notificações"));

        jScrollPane1.setViewportView(jListNotificacoes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelIniciarSessão.setText("Iniciou Sessão como");

        jLabelUserLogin.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelUserLogin.setText("Exemplo");

        jMenu3.setText("Logout");
        jMenu3.add(jSeparator3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabelIniciarSessão)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUserLogin))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserLogin)
                    .addComponent(jLabelIniciarSessão))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProcurarActionPerformed

    private void jRadioButtonNClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNClienteActionPerformed
        jRadioButtonNomeCliente.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNClienteActionPerformed

    private void jRadioButtonRelFacPagChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacPagChequeActionPerformed
        jRadioButtonRelFacPagDin.setSelected(false);
        jRadioButtonRelFacpagCartao.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelFacPagChequeActionPerformed

    private void jRadioButtonRelFacpagCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacpagCartaoActionPerformed
        jRadioButtonRelFacPagCheque.setSelected(false);
        jRadioButtonRelFacPagDin.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelFacpagCartaoActionPerformed

    private void jRadioButtonRelMPAvariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPAvariasActionPerformed
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelMPAvariasActionPerformed

    private void jButtonManRegistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManRegistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManRegistaActionPerformed

    private void jRadioButtonNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeClienteActionPerformed
        jRadioButtonNCliente.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNomeClienteActionPerformed

    private void jRadioButtonRelDiaTotalEntSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTotalEntSaiActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaTotalEntSaiActionPerformed

    private void jRadioButtonRelDiaOcupaNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaOcupaNivelActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaOcupaNivelActionPerformed

    private void jRadioButtonRelDiaTempoEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTempoEstaActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaTempoEstaActionPerformed

    private void jRadioButtonRelDiaEntEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaEntEstActionPerformed

        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaEntEstActionPerformed

    private void jRadioButtonRelDiaTemposPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTemposPagActionPerformed
         jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaTemposPagActionPerformed

    private void jRadioButtonRelDiaNBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaNBilheteActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaNBilheteActionPerformed

    private void jRadioButtonRelDiaViaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaViaturasActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelDiaViaturasActionPerformed

    private void jRadioButtonRelMPNpagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPNpagActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);

    }//GEN-LAST:event_jRadioButtonRelMPNpagActionPerformed

    private void jRadioButtonRelMPTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPTotalActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelMPTotalActionPerformed

    private void jRadioButtonRelMPNumPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPNumPerceActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelMPNumPerceActionPerformed

    private void jRadioButtonRelFacPagDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacPagDinActionPerformed
        jRadioButtonRelFacPagCheque.setSelected(false);
        jRadioButtonRelFacpagCartao.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelFacPagDinActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            Model.connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInterfacePARKUM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jALTnib;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonManRegista;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JButton jButtonRegistarCliente;
    private javax.swing.JButton jButtonRelClienteGerarRel;
    private javax.swing.JButton jButtonRelDiaGerar;
    private javax.swing.JButton jButtonRelFacGerar;
    private javax.swing.JButton jButtonRelMPGerar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonTabDistGera;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxTabDistHora;
    private javax.swing.JComboBox jComboBoxTabDistNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabelALTmatricVeic;
    private javax.swing.JLabel jLabelALTmodoEntrada;
    private javax.swing.JLabel jLabelALTnCliente;
    private javax.swing.JLabel jLabelALTnomeCliente;
    private javax.swing.JLabel jLabelIniciarSessão;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModoEntrada;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumerroCliente;
    private javax.swing.JLabel jLabelProcura1;
    private javax.swing.JLabel jLabelProcura2;
    private javax.swing.JLabel jLabelRelDia1;
    private javax.swing.JLabel jLabelRelFac1;
    private javax.swing.JLabel jLabelRelMP1;
    private javax.swing.JLabel jLabelRelMP2;
    private javax.swing.JLabel jLabelTabDist1;
    private javax.swing.JLabel jLabelTabDist2;
    private javax.swing.JLabel jLabelUserLogin;
    private javax.swing.JList jListClientesRegistados;
    private javax.swing.JList jListNotificacoes;
    private javax.swing.JList jListPagamentosAtraso;
    private javax.swing.JList jListPagamentosAtrasoCliente;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonNCliente;
    private javax.swing.JRadioButton jRadioButtonNomeCliente;
    private javax.swing.JRadioButton jRadioButtonRelClienteNentrada;
    private javax.swing.JRadioButton jRadioButtonRelClienteTemposEstacion;
    private javax.swing.JRadioButton jRadioButtonRelClienteValorMensal;
    private javax.swing.JRadioButton jRadioButtonRelDiaEntEst;
    private javax.swing.JRadioButton jRadioButtonRelDiaNBilhete;
    private javax.swing.JRadioButton jRadioButtonRelDiaOcupaNivel;
    private javax.swing.JRadioButton jRadioButtonRelDiaTempoEsta;
    private javax.swing.JRadioButton jRadioButtonRelDiaTemposPag;
    private javax.swing.JRadioButton jRadioButtonRelDiaTotalEntSai;
    private javax.swing.JRadioButton jRadioButtonRelDiaViaturas;
    private javax.swing.JRadioButton jRadioButtonRelFacPagCheque;
    private javax.swing.JRadioButton jRadioButtonRelFacPagDin;
    private javax.swing.JRadioButton jRadioButtonRelFacpagCartao;
    private javax.swing.JRadioButton jRadioButtonRelMPAvarias;
    private javax.swing.JRadioButton jRadioButtonRelMPNpag;
    private javax.swing.JRadioButton jRadioButtonRelMPNumPerce;
    private javax.swing.JRadioButton jRadioButtonRelMPTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldManNumMaq;
    private javax.swing.JTextField jTextFieldManTempo;
    private javax.swing.JTextField jTextFieldProcurar;
    private javax.swing.JTextField jTextFieldRelMPIdMaq;
    private javax.swing.JTextPane jTextPaneManDescri;
    // End of variables declaration//GEN-END:variables

}
