/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInterfaceSimulacao.java
 *
 * Created on 28/Dez/2010, 17:40:44
 */

package swing;

/**
 *
 * @author Isa
 */
public class JInterfaceSimulacao extends javax.swing.JFrame {

    /** Creates new form JInterfaceSimulacao */
    public JInterfaceSimulacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNotificacoes = new javax.swing.JList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelRegistarEntradaModosEntrada = new javax.swing.JPanel();
        jRadioButtonRegistarEntradaBilhete = new javax.swing.JRadioButton();
        jRadioButtonRegistarEntradaCliente = new javax.swing.JRadioButton();
        jPanelModoEntradaClienteRegistado = new javax.swing.JPanel();
        jTextFieldRegistarEntradaIDCliente = new javax.swing.JTextField();
        jButtonRegistarEntradaCliente = new javax.swing.JButton();
        jButtonRegistarSaidaCliente = new javax.swing.JButton();
        jPanelRegistarEntradaBilhete = new javax.swing.JPanel();
        jTextFieldRegistarEntradaBilhete = new javax.swing.JTextField();
        jButtonRegistarEntradaBilhete = new javax.swing.JButton();
        jButtonRegistarSaidaBilhete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acções"));

        jScrollPane1.setViewportView(jListNotificacoes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        jPanelRegistarEntradaModosEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo Acesso"));

        jRadioButtonRegistarEntradaBilhete.setText("Bilhete");
        jRadioButtonRegistarEntradaBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRegistarEntradaBilheteActionPerformed(evt);
            }
        });

        jRadioButtonRegistarEntradaCliente.setText("Cliente Registado");
        jRadioButtonRegistarEntradaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRegistarEntradaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistarEntradaModosEntradaLayout = new javax.swing.GroupLayout(jPanelRegistarEntradaModosEntrada);
        jPanelRegistarEntradaModosEntrada.setLayout(jPanelRegistarEntradaModosEntradaLayout);
        jPanelRegistarEntradaModosEntradaLayout.setHorizontalGroup(
            jPanelRegistarEntradaModosEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistarEntradaModosEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistarEntradaModosEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonRegistarEntradaBilhete)
                    .addComponent(jRadioButtonRegistarEntradaCliente))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanelRegistarEntradaModosEntradaLayout.setVerticalGroup(
            jPanelRegistarEntradaModosEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistarEntradaModosEntradaLayout.createSequentialGroup()
                .addComponent(jRadioButtonRegistarEntradaBilhete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonRegistarEntradaCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelModoEntradaClienteRegistado.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente Registado"));

        jTextFieldRegistarEntradaIDCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Cliente"));

        jButtonRegistarEntradaCliente.setText("Registar Entada");

        jButtonRegistarSaidaCliente.setText("Registar Saida");

        javax.swing.GroupLayout jPanelModoEntradaClienteRegistadoLayout = new javax.swing.GroupLayout(jPanelModoEntradaClienteRegistado);
        jPanelModoEntradaClienteRegistado.setLayout(jPanelModoEntradaClienteRegistadoLayout);
        jPanelModoEntradaClienteRegistadoLayout.setHorizontalGroup(
            jPanelModoEntradaClienteRegistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoEntradaClienteRegistadoLayout.createSequentialGroup()
                .addGroup(jPanelModoEntradaClienteRegistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRegistarEntradaIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(jPanelModoEntradaClienteRegistadoLayout.createSequentialGroup()
                        .addComponent(jButtonRegistarEntradaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistarSaidaCliente)))
                .addContainerGap())
        );
        jPanelModoEntradaClienteRegistadoLayout.setVerticalGroup(
            jPanelModoEntradaClienteRegistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoEntradaClienteRegistadoLayout.createSequentialGroup()
                .addComponent(jTextFieldRegistarEntradaIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanelModoEntradaClienteRegistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistarEntradaCliente)
                    .addComponent(jButtonRegistarSaidaCliente)))
        );

        jPanelRegistarEntradaBilhete.setBorder(javax.swing.BorderFactory.createTitledBorder("Bilhete"));

        jTextFieldRegistarEntradaBilhete.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero Bilhete"));

        jButtonRegistarEntradaBilhete.setText("Registar Entrada");

        jButtonRegistarSaidaBilhete.setText("Registar Saida");

        javax.swing.GroupLayout jPanelRegistarEntradaBilheteLayout = new javax.swing.GroupLayout(jPanelRegistarEntradaBilhete);
        jPanelRegistarEntradaBilhete.setLayout(jPanelRegistarEntradaBilheteLayout);
        jPanelRegistarEntradaBilheteLayout.setHorizontalGroup(
            jPanelRegistarEntradaBilheteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistarEntradaBilheteLayout.createSequentialGroup()
                .addComponent(jButtonRegistarEntradaBilhete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonRegistarSaidaBilhete))
            .addComponent(jTextFieldRegistarEntradaBilhete, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanelRegistarEntradaBilheteLayout.setVerticalGroup(
            jPanelRegistarEntradaBilheteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistarEntradaBilheteLayout.createSequentialGroup()
                .addComponent(jTextFieldRegistarEntradaBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanelRegistarEntradaBilheteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistarEntradaBilhete)
                    .addComponent(jButtonRegistarSaidaBilhete)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistarEntradaModosEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelModoEntradaClienteRegistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRegistarEntradaBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRegistarEntradaBilhete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelModoEntradaClienteRegistado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelRegistarEntradaModosEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Regitar Entradas e Saidas", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pagamentos", jPanel2);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRegistarEntradaBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRegistarEntradaBilheteActionPerformed
        jRadioButtonRegistarEntradaBilhete.setSelected(true);
        jRadioButtonRegistarEntradaCliente.setSelected(false);
        jPanelModoEntradaClienteRegistado.setEnabled(false);
        jTextFieldRegistarEntradaBilhete.setEnabled(true);
        jTextFieldRegistarEntradaIDCliente.setEnabled(false);
        jButtonRegistarEntradaBilhete.setEnabled(true);
        jButtonRegistarSaidaBilhete.setEnabled(true);
        jButtonRegistarEntradaCliente.setEnabled(false);
        jButtonRegistarSaidaCliente.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonRegistarEntradaBilheteActionPerformed

    private void jRadioButtonRegistarEntradaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRegistarEntradaClienteActionPerformed
        jRadioButtonRegistarEntradaBilhete.setSelected(false);
        jRadioButtonRegistarEntradaCliente.setSelected(true);
        jPanelModoEntradaClienteRegistado.setEnabled(true);
        jPanelRegistarEntradaBilhete.setEnabled(false);
        jTextFieldRegistarEntradaBilhete.setEnabled(false);
        jTextFieldRegistarEntradaIDCliente.setEnabled(true);
        jButtonRegistarEntradaBilhete.setEnabled(false);
        jButtonRegistarSaidaBilhete.setEnabled(false);
        jButtonRegistarEntradaCliente.setEnabled(true);
        jButtonRegistarSaidaCliente.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonRegistarEntradaClienteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInterfaceSimulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistarEntradaBilhete;
    private javax.swing.JButton jButtonRegistarEntradaCliente;
    private javax.swing.JButton jButtonRegistarSaidaBilhete;
    private javax.swing.JButton jButtonRegistarSaidaCliente;
    private javax.swing.JList jListNotificacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelModoEntradaClienteRegistado;
    private javax.swing.JPanel jPanelRegistarEntradaBilhete;
    private javax.swing.JPanel jPanelRegistarEntradaModosEntrada;
    private javax.swing.JRadioButton jRadioButtonRegistarEntradaBilhete;
    private javax.swing.JRadioButton jRadioButtonRegistarEntradaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldRegistarEntradaBilhete;
    private javax.swing.JTextField jTextFieldRegistarEntradaIDCliente;
    // End of variables declaration//GEN-END:variables

}
