-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO maquinas  VALUES ('11','1','Ao lado da porta de saida','500');

INSERT INTO maquinas  VALUES ('12','1','','500');

INSERT INTO maquinas  VALUES ('21','2','','500');

INSERT INTO maquinas  VALUES ('31','3','','500');

INSERT INTO maquinas  VALUES ('41','4','Ao lado do lugar 414','500');

INSERT INTO maquinas  VALUES ('51','5','','500');

