-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO registos_manutencao  VALUES ('11','Colocacao de papel. Recolha de 322euros',to_date('2010-11-01 12:00:00','yyyy-mm-dd hh24:mi:ss'),'12','F02');

INSERT INTO registos_manutencao  VALUES ('12','Colocacao de tinta. Recolha de 530euros',to_date('2010-12-01 12:00:00','yyyy-mm-dd hh24:mi:ss'),'22','F07');

INSERT INTO registos_manutencao  VALUES ('31','Recolha de 210euros',to_date('2010-10-01 12:00:00','yyyy-mm-dd hh24:mi:ss'),'6','F01');

INSERT INTO registos_manutencao  VALUES ('21','Colocacao de papel',to_date('2010-11-15 12:00:00','yyyy-mm-dd hh24:mi:ss'),'5','F02');

INSERT INTO registos_manutencao  VALUES ('41','Colocacao de papel',to_date('2010-12-15 12:00:00','yyyy-mm-dd hh24:mi:ss'),'7','F03');

INSERT INTO registos_manutencao  VALUES ('41','Recolha de 150uros',to_date('2010-10-15 12:00:00','yyyy-mm-dd hh24:mi:ss'),'8','F01');

INSERT INTO registos_manutencao  VALUES ('51','Colocacao de tinta',to_date('2010-10-20 12:00:00','yyyy-mm-dd hh24:mi:ss'),'16','F05');

INSERT INTO registos_manutencao  VALUES ('51','Recolha de 250euros',to_date('2010-12-22 12:00:00','yyyy-mm-dd hh24:mi:ss'),'5','F02');

/*insert into registos VALUES ('0001',to_date('2009-01-23 14:30','yyyy-mm-dd hh24:mi') , null,null,null);*/

