-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO lugares VALUES ('101','1','1');

INSERT INTO lugares VALUES ('102','1','1');

INSERT INTO lugares VALUES ('103','1','1');

INSERT INTO lugares VALUES ('104','1','1');

INSERT INTO lugares VALUES ('105','1','1');

INSERT INTO lugares VALUES ('106','1','1');

INSERT INTO lugares VALUES ('107','1','1');

INSERT INTO lugares VALUES ('108','1','1');

INSERT INTO lugares VALUES ('109','1','1');

INSERT INTO lugares VALUES ('110','1','1');

INSERT INTO lugares VALUES ('111','1','0');

INSERT INTO lugares VALUES ('112','1','0');

INSERT INTO lugares VALUES ('113','1','0');

INSERT INTO lugares VALUES ('114','1','0');

INSERT INTO lugares VALUES ('115','1','0');

INSERT INTO lugares VALUES ('116','1','0');

INSERT INTO lugares VALUES ('117','1','0');

INSERT INTO lugares VALUES ('118','1','0');

INSERT INTO lugares VALUES ('119','1','0');

INSERT INTO lugares VALUES ('120','1','0');

INSERT INTO lugares VALUES ('121','1','0');

INSERT INTO lugares VALUES ('122','1','0');

INSERT INTO lugares VALUES ('123','1','0');

INSERT INTO lugares VALUES ('124','1','0');

INSERT INTO lugares VALUES ('125','1','0');

INSERT INTO lugares VALUES ('126','1','0');

INSERT INTO lugares VALUES ('127','1','0');

INSERT INTO lugares VALUES ('128','1','0');

INSERT INTO lugares VALUES ('129','1','0');

INSERT INTO lugares VALUES ('130','1','0');

INSERT INTO lugares VALUES ('131','1','0');

INSERT INTO lugares VALUES ('132','1','0');

INSERT INTO lugares VALUES ('133','1','0');

INSERT INTO lugares VALUES ('134','1','0');

INSERT INTO lugares VALUES ('135','1','0');

INSERT INTO lugares VALUES ('136','1','0');

INSERT INTO lugares VALUES ('137','1','0');

INSERT INTO lugares VALUES ('138','1','0');

INSERT INTO lugares VALUES ('139','1','0');

INSERT INTO lugares VALUES ('140','1','0');

INSERT INTO lugares VALUES ('141','1','0');

INSERT INTO lugares VALUES ('142','1','0');

INSERT INTO lugares VALUES ('143','1','0');

INSERT INTO lugares VALUES ('144','1','0');

INSERT INTO lugares VALUES ('145','1','0');

INSERT INTO lugares VALUES ('146','1','0');

INSERT INTO lugares VALUES ('147','1','0');

INSERT INTO lugares VALUES ('148','1','0');

INSERT INTO lugares VALUES ('149','1','0');

INSERT INTO lugares VALUES ('150','1','0');

INSERT INTO lugares VALUES ('201','2','1');

INSERT INTO lugares VALUES ('202','2','1');

INSERT INTO lugares VALUES ('203','2','1');

INSERT INTO lugares VALUES ('204','2','1');

INSERT INTO lugares VALUES ('205','2','1');

INSERT INTO lugares VALUES ('206','2','1');

INSERT INTO lugares VALUES ('207','2','1');

INSERT INTO lugares VALUES ('208','2','1');

INSERT INTO lugares VALUES ('209','2','1');

INSERT INTO lugares VALUES ('210','2','1');

INSERT INTO lugares VALUES ('211','2','0');

INSERT INTO lugares VALUES ('212','2','0');

INSERT INTO lugares VALUES ('213','2','0');

INSERT INTO lugares VALUES ('214','2','0');

INSERT INTO lugares VALUES ('215','2','0');

INSERT INTO lugares VALUES ('216','2','0');

INSERT INTO lugares VALUES ('217','2','0');

INSERT INTO lugares VALUES ('218','2','0');

INSERT INTO lugares VALUES ('219','2','0');

INSERT INTO lugares VALUES ('220','2','0');

INSERT INTO lugares VALUES ('221','2','0');

INSERT INTO lugares VALUES ('222','2','0');

INSERT INTO lugares VALUES ('223','2','0');

INSERT INTO lugares VALUES ('224','2','0');

INSERT INTO lugares VALUES ('225','2','0');

INSERT INTO lugares VALUES ('226','2','0');

INSERT INTO lugares VALUES ('227','2','0');

INSERT INTO lugares VALUES ('228','2','0');

INSERT INTO lugares VALUES ('229','2','0');

INSERT INTO lugares VALUES ('230','2','0');

INSERT INTO lugares VALUES ('231','2','0');

INSERT INTO lugares VALUES ('232','2','0');

INSERT INTO lugares VALUES ('233','2','0');

INSERT INTO lugares VALUES ('234','2','0');

INSERT INTO lugares VALUES ('235','2','0');

INSERT INTO lugares VALUES ('236','2','0');

INSERT INTO lugares VALUES ('237','2','0');

INSERT INTO lugares VALUES ('238','2','0');

INSERT INTO lugares VALUES ('239','2','0');

INSERT INTO lugares VALUES ('240','2','0');

INSERT INTO lugares VALUES ('241','2','0');

INSERT INTO lugares VALUES ('242','2','0');

INSERT INTO lugares VALUES ('243','2','0');

INSERT INTO lugares VALUES ('244','2','0');

INSERT INTO lugares VALUES ('245','2','0');

INSERT INTO lugares VALUES ('246','2','0');

INSERT INTO lugares VALUES ('247','2','0');

INSERT INTO lugares VALUES ('248','2','0');

INSERT INTO lugares VALUES ('249','2','0');

INSERT INTO lugares VALUES ('250','2','0');

INSERT INTO lugares VALUES ('301','3','1');

INSERT INTO lugares VALUES ('302','3','1');

INSERT INTO lugares VALUES ('303','3','1');

INSERT INTO lugares VALUES ('304','3','1');

INSERT INTO lugares VALUES ('305','3','1');

INSERT INTO lugares VALUES ('306','3','0');

INSERT INTO lugares VALUES ('307','3','0');

INSERT INTO lugares VALUES ('308','3','0');

INSERT INTO lugares VALUES ('309','3','0');

INSERT INTO lugares VALUES ('310','3','0');

INSERT INTO lugares VALUES ('311','3','0');

INSERT INTO lugares VALUES ('312','3','0');

INSERT INTO lugares VALUES ('313','3','0');

INSERT INTO lugares VALUES ('314','3','0');

INSERT INTO lugares VALUES ('315','3','0');

INSERT INTO lugares VALUES ('316','3','0');

INSERT INTO lugares VALUES ('317','3','0');

INSERT INTO lugares VALUES ('318','3','0');

INSERT INTO lugares VALUES ('319','3','0');

INSERT INTO lugares VALUES ('320','3','0');

INSERT INTO lugares VALUES ('321','3','0');

INSERT INTO lugares VALUES ('322','3','0');

INSERT INTO lugares VALUES ('323','3','0');

INSERT INTO lugares VALUES ('324','3','0');

INSERT INTO lugares VALUES ('325','3','0');

INSERT INTO lugares VALUES ('326','3','0');

INSERT INTO lugares VALUES ('327','3','0');

INSERT INTO lugares VALUES ('328','3','0');

INSERT INTO lugares VALUES ('329','3','0');

INSERT INTO lugares VALUES ('330','3','0');

INSERT INTO lugares VALUES ('331','3','0');

INSERT INTO lugares VALUES ('332','3','0');

INSERT INTO lugares VALUES ('333','3','0');

INSERT INTO lugares VALUES ('334','3','0');

INSERT INTO lugares VALUES ('335','3','0');

INSERT INTO lugares VALUES ('336','3','0');

INSERT INTO lugares VALUES ('337','3','0');

INSERT INTO lugares VALUES ('338','3','0');

INSERT INTO lugares VALUES ('339','3','0');

INSERT INTO lugares VALUES ('340','3','0');

INSERT INTO lugares VALUES ('341','3','0');

INSERT INTO lugares VALUES ('342','3','0');

INSERT INTO lugares VALUES ('343','3','0');

INSERT INTO lugares VALUES ('344','3','0');

INSERT INTO lugares VALUES ('345','3','0');

INSERT INTO lugares VALUES ('346','3','0');

INSERT INTO lugares VALUES ('347','3','0');

INSERT INTO lugares VALUES ('348','3','0');

INSERT INTO lugares VALUES ('349','3','0');

INSERT INTO lugares VALUES ('350','3','0');

INSERT INTO lugares VALUES ('401','4','1');

INSERT INTO lugares VALUES ('402','4','1');

INSERT INTO lugares VALUES ('403','4','1');

INSERT INTO lugares VALUES ('404','4','1');

INSERT INTO lugares VALUES ('405','4','1');

INSERT INTO lugares VALUES ('406','4','0');

INSERT INTO lugares VALUES ('407','4','0');

INSERT INTO lugares VALUES ('408','4','0');

INSERT INTO lugares VALUES ('409','4','0');

INSERT INTO lugares VALUES ('410','4','0');

INSERT INTO lugares VALUES ('411','4','0');

INSERT INTO lugares VALUES ('412','4','0');

INSERT INTO lugares VALUES ('413','4','0');

INSERT INTO lugares VALUES ('414','4','0');

INSERT INTO lugares VALUES ('415','4','0');

INSERT INTO lugares VALUES ('416','4','0');

INSERT INTO lugares VALUES ('417','4','0');

INSERT INTO lugares VALUES ('418','4','0');

INSERT INTO lugares VALUES ('419','4','0');

INSERT INTO lugares VALUES ('420','4','0');

INSERT INTO lugares VALUES ('421','4','0');

INSERT INTO lugares VALUES ('422','4','0');

INSERT INTO lugares VALUES ('423','4','0');

INSERT INTO lugares VALUES ('424','4','0');

INSERT INTO lugares VALUES ('425','4','0');

INSERT INTO lugares VALUES ('426','4','0');

INSERT INTO lugares VALUES ('427','4','0');

INSERT INTO lugares VALUES ('428','4','0');

INSERT INTO lugares VALUES ('429','4','0');

INSERT INTO lugares VALUES ('430','4','0');

INSERT INTO lugares VALUES ('431','4','0');

INSERT INTO lugares VALUES ('432','4','0');

INSERT INTO lugares VALUES ('433','4','0');

INSERT INTO lugares VALUES ('434','4','0');

INSERT INTO lugares VALUES ('435','4','0');

INSERT INTO lugares VALUES ('436','4','0');

INSERT INTO lugares VALUES ('437','4','0');

INSERT INTO lugares VALUES ('438','4','0');

INSERT INTO lugares VALUES ('439','4','0');

INSERT INTO lugares VALUES ('440','4','0');

INSERT INTO lugares VALUES ('441','4','0');

INSERT INTO lugares VALUES ('442','4','0');

INSERT INTO lugares VALUES ('443','4','0');

INSERT INTO lugares VALUES ('444','4','0');

INSERT INTO lugares VALUES ('445','4','0');

INSERT INTO lugares VALUES ('446','4','0');

INSERT INTO lugares VALUES ('447','4','0');

INSERT INTO lugares VALUES ('448','4','0');

INSERT INTO lugares VALUES ('449','4','0');

INSERT INTO lugares VALUES ('450','4','0');

INSERT INTO lugares VALUES ('501','5','1');

INSERT INTO lugares VALUES ('502','5','1');

INSERT INTO lugares VALUES ('503','5','1');

INSERT INTO lugares VALUES ('504','5','1');

INSERT INTO lugares VALUES ('505','5','1');

INSERT INTO lugares VALUES ('506','5','0');

INSERT INTO lugares VALUES ('507','5','0');

INSERT INTO lugares VALUES ('508','5','0');

INSERT INTO lugares VALUES ('509','5','0');

INSERT INTO lugares VALUES ('510','5','0');

INSERT INTO lugares VALUES ('511','5','0');

INSERT INTO lugares VALUES ('512','5','0');

INSERT INTO lugares VALUES ('513','5','0');

INSERT INTO lugares VALUES ('514','5','0');

INSERT INTO lugares VALUES ('515','5','0');

INSERT INTO lugares VALUES ('516','5','0');

INSERT INTO lugares VALUES ('517','5','0');

INSERT INTO lugares VALUES ('518','5','0');

INSERT INTO lugares VALUES ('519','5','0');

INSERT INTO lugares VALUES ('520','5','0');

INSERT INTO lugares VALUES ('521','5','0');

INSERT INTO lugares VALUES ('522','5','0');

INSERT INTO lugares VALUES ('523','5','0');

INSERT INTO lugares VALUES ('524','5','0');

INSERT INTO lugares VALUES ('525','5','0');

INSERT INTO lugares VALUES ('526','5','0');

INSERT INTO lugares VALUES ('527','5','0');

INSERT INTO lugares VALUES ('528','5','0');

INSERT INTO lugares VALUES ('529','5','0');

INSERT INTO lugares VALUES ('530','5','0');

INSERT INTO lugares VALUES ('531','5','0');

INSERT INTO lugares VALUES ('532','5','0');

INSERT INTO lugares VALUES ('533','5','0');

INSERT INTO lugares VALUES ('534','5','0');

INSERT INTO lugares VALUES ('535','5','0');

INSERT INTO lugares VALUES ('536','5','0');

INSERT INTO lugares VALUES ('537','5','0');

INSERT INTO lugares VALUES ('538','5','0');

INSERT INTO lugares VALUES ('539','5','0');

INSERT INTO lugares VALUES ('540','5','0');

INSERT INTO lugares VALUES ('541','5','0');

INSERT INTO lugares VALUES ('542','5','0');

INSERT INTO lugares VALUES ('543','5','0');

INSERT INTO lugares VALUES ('544','5','0');

INSERT INTO lugares VALUES ('545','5','0');

INSERT INTO lugares VALUES ('546','5','0');

INSERT INTO lugares VALUES ('547','5','0');

INSERT INTO lugares VALUES ('548','5','0');

INSERT INTO lugares VALUES ('549','5','0');

INSERT INTO lugares VALUES ('550','5','0');

