/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInterfacePARKUM.java
 *
 * Created on 27/Dez/2010, 18:58:25
 */
package swing;

import sci.Model;
import sci.Query;
import clientes.FichaCliente;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import sci.BaseDados;
import sci.GestaoRelatorios;

/**
 *
 * @author Hugo
 */
public class JInterfacePARKUM extends javax.swing.JFrame implements Observer {

    ResultSet rSet = null;
    FichaCliente cliente = new FichaCliente();

    /** Creates new form JInterfacePARKUM */
    public JInterfacePARKUM() throws SQLException {
        //Util.centerOnScreen(this);
         try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar o \"Skin\" padrão. Definindo o padrão original.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        jRadioButtonNCliente.setSelected(true);
        jRadioButtonRelClienteNentrada.setSelected(true);
        jRadioButtonRelDiaTotalEntSai.setSelected(true);
        jRadioButtonRelFacPagDin.setSelected(true);
        jRadioButtonRelMPNpag.setSelected(true);
        jTextFieldNomeCliente.setEditable(false);
        jTextFieldidCliente.setEditable(false);
        jTextFieldNib.setEditable(false);
        jTextFieldMatricula.setEditable(false);
        jTextFieldModoEntrada.setEditable(false);

        String pag = "";
        DefaultListModel model = new DefaultListModel();
        rSet = Query.queryClientes();
        
        while (rSet.next()){
            pag = Query.pagamentoEmAtraso(rSet.getString(1));
            model.addElement(pag);
        }
        jListPagamentosAtraso.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelProcura1 = new javax.swing.JLabel();
        jTextFieldProcurar = new javax.swing.JTextField();
        jButtonProcurar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButtonNCliente = new javax.swing.JRadioButton();
        jRadioButtonNomeCliente = new javax.swing.JRadioButton();
        jButtonRegistarCliente = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jComboBoxTipoCliente = new javax.swing.JComboBox();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabelNumerroCliente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabelModoEntrada = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldidCliente = new javax.swing.JTextField();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldNib = new javax.swing.JTextField();
        jTextFieldModoEntrada = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jRadioButtonRelClienteNentrada = new javax.swing.JRadioButton();
        jRadioButtonRelClienteValorMensal = new javax.swing.JRadioButton();
        jRadioButtonRelClienteTemposEstacion = new javax.swing.JRadioButton();
        jButtonRelClienteGerarRel = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPagamentosAtrasoCliente = new javax.swing.JList();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClientesRegistados = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPagamentosAtraso = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jButtonRelDiaGerar = new javax.swing.JButton();
        jRadioButtonRelDiaTotalEntSai = new javax.swing.JRadioButton();
        jRadioButtonRelDiaOcupaNivel = new javax.swing.JRadioButton();
        jRadioButtonRelDiaTempoEsta = new javax.swing.JRadioButton();
        jRadioButtonRelDiaEntEst = new javax.swing.JRadioButton();
        jRadioButtonRelDiaTemposPag = new javax.swing.JRadioButton();
        jRadioButtonRelDiaNBilhete = new javax.swing.JRadioButton();
        jRadioButtonRelDiaViaturas = new javax.swing.JRadioButton();
        jLabelRelDia1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSelecDia = new javax.swing.JTextField();
        jTextFieldSelectAno = new javax.swing.JTextField();
        jTextFieldSelecMes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButtonRelMPGerar = new javax.swing.JButton();
        jRadioButtonRelMPNpag = new javax.swing.JRadioButton();
        jRadioButtonRelMPTotal = new javax.swing.JRadioButton();
        jRadioButtonRelMPNumPerce = new javax.swing.JRadioButton();
        jRadioButtonRelMPAvarias = new javax.swing.JRadioButton();
        jLabelRelMP1 = new javax.swing.JLabel();
        jTextFieldRelMPIdMaq = new javax.swing.JTextField();
        jLabelRelMP2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabelRelFac1 = new javax.swing.JLabel();
        jRadioButtonRelFacPagDin = new javax.swing.JRadioButton();
        jRadioButtonRelFacpagCartao = new javax.swing.JRadioButton();
        jRadioButtonRelFacPagCheque = new javax.swing.JRadioButton();
        jButtonRelFacGerar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButtonTabDistGera = new javax.swing.JButton();
        jComboBoxTabDistHora = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabelTabDist1 = new javax.swing.JLabel();
        jLabelTabDist2 = new javax.swing.JLabel();
        jComboBoxTabDistNivel = new javax.swing.JComboBox();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListTabelaDistribuicoes = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jTextFieldManNumMaq = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldManTempo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonManRegista = new javax.swing.JButton();
        jTextFieldIDFuncionario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneManDescri = new javax.swing.JTextPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRegPagNCliente = new javax.swing.JTextField();
        jComboBoxRegisPagForma = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRegPagMontante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonRegistarPagamento = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldRegisPagData = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonRegistarPagamentomulta = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldMultaBilhete = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Procura de Clientes"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProcura1.setText("A procura será feita de acordo com o modo de ");
        jPanel6.add(jLabelProcura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextFieldProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProcurarActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jButtonProcurar.setText("Procurar");
        jButtonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel6.setText(" visualização em que está!");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 250, 110));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Visualização"));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jRadioButtonNCliente.setText("Nº de Cliente");
        jRadioButtonNCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNClienteActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonNCliente, java.awt.BorderLayout.CENTER);

        jRadioButtonNomeCliente.setText("Nome do Cliente");
        jRadioButtonNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeClienteActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonNomeCliente, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 70));

        jButtonRegistarCliente.setText("Registar Novo Cliente");
        jButtonRegistarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonRegistarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jButtonEditar.setText("Editar Cliente");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jComboBoxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os Clientes" }));
        try {
            rSet = sci.Query.queryModosEntrada();

            while (rSet.next())
            jComboBoxTipoCliente.addItem(rSet.getString(2));
        }
        catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }
        jComboBoxTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, -1));

        jLabelNumerroCliente.setText("Número do Cliente");

        jLabelNomeCliente.setText("Nome do Cliente");

        jLabelModoEntrada.setText("Modo de Entrada");

        jLabelMatricula.setText("Matricula do Veiculo");

        jLabel1.setText("NIB");

        jTextFieldidCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidClienteActionPerformed(evt);
            }
        });

        jTextFieldModoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumerroCliente)
                    .addComponent(jLabelMatricula)
                    .addComponent(jLabelModoEntrada)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNib, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jTextFieldModoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jTextFieldidCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumerroCliente)
                    .addComponent(jTextFieldidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModoEntrada)
                    .addComponent(jTextFieldModoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatricula)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Informações do Cliente", jPanel7);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButtonRelClienteNentrada.setText("Nº de entradas");
        jRadioButtonRelClienteNentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelClienteNentradaActionPerformed(evt);
            }
        });
        jPanel13.add(jRadioButtonRelClienteNentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        jRadioButtonRelClienteValorMensal.setText("Valor mensal a pagar");
        jRadioButtonRelClienteValorMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelClienteValorMensalActionPerformed(evt);
            }
        });
        jPanel13.add(jRadioButtonRelClienteValorMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        jRadioButtonRelClienteTemposEstacion.setText("Tempos médios de estacionamento");
        jRadioButtonRelClienteTemposEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelClienteTemposEstacionActionPerformed(evt);
            }
        });
        jPanel13.add(jRadioButtonRelClienteTemposEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, -1));

        jButtonRelClienteGerarRel.setText("Gerar Relatório");
        jButtonRelClienteGerarRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelClienteGerarRelActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonRelClienteGerarRel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 134, 140));

        jTabbedPane3.addTab("Relatórios sobre o Cliente", jPanel13);

        jScrollPane4.setViewportView(jListPagamentosAtrasoCliente);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Lista de Pagamentos em Atraso do Cliente", jPanel14);

        jPanel3.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 490, -1));

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Registados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListClientesRegistados.setBackground(java.awt.SystemColor.control);
        try {
            rSet = sci.Query.queryClientes();
            DefaultListModel model = new DefaultListModel();
            while (rSet.next())
            model.addElement(rSet.getString(1));
            jListClientesRegistados.setModel(model);
        }
        catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }
        jListClientesRegistados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListClientesRegistadosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListClientesRegistados);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 350));

        jTabbedPane1.addTab("Gestão de Clientes", jPanel3);

        jScrollPane5.setViewportView(jListPagamentosAtraso);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listagem de Pagamentos em Atraso", jPanel15);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRelDiaGerar.setText("Gerar Relatório");
        jButtonRelDiaGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelDiaGerarActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonRelDiaGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 80));

        jRadioButtonRelDiaTotalEntSai.setText("Total de entradas e saidas");
        jRadioButtonRelDiaTotalEntSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTotalEntSaiActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaTotalEntSai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jRadioButtonRelDiaOcupaNivel.setText("Ocupações por nível");
        jRadioButtonRelDiaOcupaNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaOcupaNivelActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaOcupaNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        jRadioButtonRelDiaTempoEsta.setText("Tempos de estacionamento");
        jRadioButtonRelDiaTempoEsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTempoEstaActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaTempoEsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jRadioButtonRelDiaEntEst.setText("Tempos entre a entrada e estacionamento, por nível");
        jRadioButtonRelDiaEntEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaEntEstActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaEntEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jRadioButtonRelDiaTemposPag.setText("Tempos entre pagamento do bilhete de parque e efectiva saída");
        jRadioButtonRelDiaTemposPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaTemposPagActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaTemposPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jRadioButtonRelDiaNBilhete.setText("Número de bilhetes estraviados");
        jRadioButtonRelDiaNBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaNBilheteActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaNBilhete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jRadioButtonRelDiaViaturas.setText("Viaturas que não entraram nem sairam (relativamente aos clientes registados)");
        jRadioButtonRelDiaViaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelDiaViaturasActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButtonRelDiaViaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabelRelDia1.setText("Selecione o tipo de relatório que pretende obter:");
        jPanel9.add(jLabelRelDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecção do Dia"));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Insira o dia, mês e ano que pretende:");
        jPanel16.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setText("Dia:");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jTextFieldSelecDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSelecDiaActionPerformed(evt);
            }
        });
        jPanel16.add(jTextFieldSelecDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, 87, -1));
        jPanel16.add(jTextFieldSelectAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 96, 88, -1));
        jPanel16.add(jTextFieldSelecMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 96, 87, -1));

        jLabel4.setText("Mês:");
        jPanel16.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel5.setText("Ano:");
        jPanel16.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 310, 150));

        jTabbedPane2.addTab("Relatórios Diários", jPanel9);

        jButtonRelMPGerar.setText("Gerar Relatório");
        jButtonRelMPGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelMPGerarActionPerformed(evt);
            }
        });

        jRadioButtonRelMPNpag.setText("Número de pagamentos, por tipo");
        jRadioButtonRelMPNpag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPNpagActionPerformed(evt);
            }
        });

        jRadioButtonRelMPTotal.setText("Total recebido por cada tipo de pagamento (dinheiro ou cartão magnético)");
        jRadioButtonRelMPTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPTotalActionPerformed(evt);
            }
        });

        jRadioButtonRelMPNumPerce.setText("Número e percentagem de recibos emitido e o seu total");
        jRadioButtonRelMPNumPerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPNumPerceActionPerformed(evt);
            }
        });

        jRadioButtonRelMPAvarias.setText("Número de avarias e operações de manutenção registadas");
        jRadioButtonRelMPAvarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelMPAvariasActionPerformed(evt);
            }
        });

        jLabelRelMP1.setText("Insira o nº de indentificação da máquina que pretende obter o relatório:");

        jLabelRelMP2.setText("Selecione o tipo de relatório que pretende obter:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRelMP2)
                    .addComponent(jRadioButtonRelMPNpag)
                    .addComponent(jRadioButtonRelMPTotal)
                    .addComponent(jRadioButtonRelMPNumPerce)
                    .addComponent(jRadioButtonRelMPAvarias)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabelRelMP1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRelMPIdMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124)
                .addComponent(jButtonRelMPGerar)
                .addGap(157, 157, 157))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRelMP1)
                            .addComponent(jTextFieldRelMPIdMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelRelMP2)
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButtonRelMPNpag)
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButtonRelMPTotal)
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButtonRelMPNumPerce)
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButtonRelMPAvarias))
                    .addComponent(jButtonRelMPGerar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Relatórios Máquinas de Pagamento", jPanel10);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));

        jLabelRelFac1.setText("Selecione o tipo de relatório que pretende obter:");

        jRadioButtonRelFacPagDin.setText("Facturação de pagamentos com dinheiro");
        jRadioButtonRelFacPagDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacPagDinActionPerformed(evt);
            }
        });

        jRadioButtonRelFacpagCartao.setText("Facturação de pagamentos com cartão magnético");
        jRadioButtonRelFacpagCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacpagCartaoActionPerformed(evt);
            }
        });

        jRadioButtonRelFacPagCheque.setText("Facturação de pagamentos com cheque");
        jRadioButtonRelFacPagCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelFacPagChequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRelFac1)
                    .addComponent(jRadioButtonRelFacPagDin)
                    .addComponent(jRadioButtonRelFacpagCartao)
                    .addComponent(jRadioButtonRelFacPagCheque))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelFac1)
                .addGap(36, 36, 36)
                .addComponent(jRadioButtonRelFacPagDin)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonRelFacpagCartao)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonRelFacPagCheque)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel24.add(jPanel23);

        jButtonRelFacGerar.setText("Gerar Relatório");
        jButtonRelFacGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelFacGerarActionPerformed(evt);
            }
        });
        jPanel24.add(jButtonRelFacGerar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 112, 31, 136);
        jPanel12.add(jPanel24, gridBagConstraints);

        jTabbedPane2.addTab("Relatórios de Facturação", jPanel12);

        jButtonTabDistGera.setText("Gerar Tabela");
        jButtonTabDistGera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabDistGeraActionPerformed(evt);
            }
        });

        jComboBoxTabDistHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel12.setText("h");

        jLabelTabDist1.setText("Escolha o nível que pretende obter o relatório:");

        jLabelTabDist2.setText("Escolha a hora do dia que pretende obter o relatório");

        try {
            rSet = sci.Query.queryPisos();

            while (rSet.next())
            jComboBoxTabDistNivel.addItem(rSet.getString(1));
        }
        catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }
        jComboBoxTabDistNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabDistNivelActionPerformed(evt);
            }
        });

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de Distribuição de Lugar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(jListTabelaDistribuicoes);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jComboBoxTabDistHora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonTabDistGera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTabDist2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxTabDistNivel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelTabDist1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelTabDist1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTabDistNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabelTabDist2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxTabDistHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jButtonTabDistGera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tabela Distribuição de Ocupações", jPanel11);

        jPanel4.add(jTabbedPane2);

        jTabbedPane1.addTab("Relatórios", jPanel4);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 21);
        jPanel5.add(jPanel18, gridBagConstraints);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Preencha os campos que se seguem para regitar a manutenção");
        jPanel22.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel16.setText("Identificação da máquina:");

        jLabel17.setText("Tempo gasto (em minutos):");

        jButtonManRegista.setText("Registar Manutenção");
        jButtonManRegista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManRegistaActionPerformed(evt);
            }
        });

        jLabel13.setText("Identificação do Funcionário");

        jLabel14.setText("Hora da Manutenção");

        jLabel18.setText("(aaaa-mm-dd hh:mm:ss)");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonManRegista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldManNumMaq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldManTempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldManNumMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldManTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManRegista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel22.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 210, -1));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição da Manutenção"));

        jTextPaneManDescri.setBackground(java.awt.SystemColor.control);
        jTextPaneManDescri.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane3.setViewportView(jTextPaneManDescri);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel22.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 41, -1, 250));

        jPanel5.add(jPanel22, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Manutenção", jPanel5);

        jPanel17.setLayout(new java.awt.GridBagLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registar Pagamentos Automáticos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel7.setText("Registe um novo pagamento preenchendo os campos ");

        jLabel8.setText("Número do Cliente");

        try {
            rSet = sci.Query.queryModosPagamento();

            while (rSet.next())
            jComboBoxRegisPagForma.addItem(rSet.getString(2));
        }
        catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }

        jLabel9.setText("Forma de Pagamento");

        jLabel10.setText("Montante a Pagar");

        jLabel11.setText("Euros");

        jButtonRegistarPagamento.setText("Registar Pagamento");
        jButtonRegistarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarPagamentoActionPerformed(evt);
            }
        });

        jLabel19.setText("Data do Pagamento  (aaaa-mm-dd hh:mm:ss)");

        jLabel20.setText("que se seguem");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldRegisPagData, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jTextFieldRegPagMontante, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxRegisPagForma, 0, 196, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jButtonRegistarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldRegPagNCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldRegPagNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxRegisPagForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldRegPagMontante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRegisPagData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel17.add(jPanel19, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamentos Multas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButtonRegistarPagamentomulta.setText("Registar Pagamento");
        jButtonRegistarPagamentomulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarPagamentomultaActionPerformed(evt);
            }
        });

        jLabel22.setText("ID Bilhete:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonRegistarPagamentomulta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMultaBilhete, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldMultaBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jButtonRegistarPagamentomulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel17.add(jPanel2, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Registar Pagamento", jPanel17);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, 400));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, -1, 11));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/logoParkum.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManRegistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManRegistaActionPerformed

        String idFuncionario = jTextFieldIDFuncionario.getText();
        String idMaquina = jTextFieldManNumMaq.getText();
        String tempoMan = jTextFieldManTempo.getText();
        String desc = jTextPaneManDescri.getText();
        String hora_manutencao = jTextFieldHora.getText();

        String msgERRO = "";
            if (idFuncionario.equalsIgnoreCase(""))                 msgERRO = msgERRO + "Falta inserir o número do Funcionário\n";
            if (idMaquina.equalsIgnoreCase(""))                     msgERRO = msgERRO + "Falta inserir o número da Máquina\n";
            if (tempoMan.equalsIgnoreCase(""))                      msgERRO = msgERRO + "Falta inserir o tempo da manutenção\n";
            if (desc.equalsIgnoreCase(""))                          msgERRO = msgERRO + "Falta inserir a operação efectuada\n";
            System.out.println(msgERRO);

        if (msgERRO.equalsIgnoreCase("") == false) {
            JOptionPane.showMessageDialog(null, msgERRO, "Erro ao registar manutenção", 1);
            }
        else {
            try {
                BaseDados.registarManutencao(idMaquina, desc, hora_manutencao, tempoMan, idFuncionario);
                //Query.adicionarManutencao(idMaquina, desc, hora_manutencao, tempoMan, idFuncionario);
            } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }

                JOptionPane.showMessageDialog(null, "Manuetenção adicionada com sucesso!", "Manutenção adicionada", 1);
                JInterfacePARKUM.this.dispose();

            }
}//GEN-LAST:event_jButtonManRegistaActionPerformed

    private void jComboBoxTabDistNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabDistNivelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxTabDistNivelActionPerformed

    private void jButtonTabDistGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabDistGeraActionPerformed

        String nivel = jComboBoxTabDistNivel.getSelectedItem().toString();
        String hora = jComboBoxTabDistHora.getSelectedItem().toString();
        String dia = "03";
        String mes = "12";
        String ano = "2010";
        try {
            
            DefaultListModel model = new DefaultListModel();

            rSet = GestaoRelatorios.lugaresOcupadosPorNivel(nivel, hora, dia, mes, ano);
            while(rSet.next()){
                model.addElement("LUGAR: "+rSet.getString(1)+"     ESTADA: OCUPADO");
            }

            rSet = GestaoRelatorios.lugaresLivresPorNivel(nivel, hora, dia, mes, ano);
            while(rSet.next()){
                model.addElement("LUGAR: "+rSet.getString(1)+"     ESTADO: LIVRE");
            }

            jListTabelaDistribuicoes.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }


/*
        try {
    rSet = sci.Query.queryClientes();
    DefaultListModel model = new DefaultListModel();
    while (rSet.next())
        model.addElement(rSet.getString(1));
    jListClientesRegistados.setModel(model);
}
catch (SQLException ex) { Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex); }
*/







}//GEN-LAST:event_jButtonTabDistGeraActionPerformed

    private void jRadioButtonRelFacPagChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacPagChequeActionPerformed
        jRadioButtonRelFacPagDin.setSelected(false);
        jRadioButtonRelFacpagCartao.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelFacPagChequeActionPerformed

    private void jRadioButtonRelFacpagCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacpagCartaoActionPerformed
        jRadioButtonRelFacPagCheque.setSelected(false);
        jRadioButtonRelFacPagDin.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelFacpagCartaoActionPerformed

    private void jRadioButtonRelFacPagDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelFacPagDinActionPerformed
        jRadioButtonRelFacPagCheque.setSelected(false);
        jRadioButtonRelFacpagCartao.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelFacPagDinActionPerformed

    private void jButtonRelFacGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelFacGerarActionPerformed
        String rel="";

         try {
                if (jRadioButtonRelFacPagDin.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosFacturacao(1);
                if (jRadioButtonRelFacpagCartao.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosFacturacao(3);
                if (jRadioButtonRelFacPagCheque.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosFacturacao(2);
            } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }
        JOptionPane.showMessageDialog(null, rel, "Relatorio",1);
        System.out.println(rel);
}//GEN-LAST:event_jButtonRelFacGerarActionPerformed

    private void jRadioButtonRelMPAvariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPAvariasActionPerformed
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelMPAvariasActionPerformed

    private void jRadioButtonRelMPNumPerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPNumPerceActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelMPNumPerceActionPerformed

    private void jRadioButtonRelMPTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPTotalActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPNpag.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelMPTotalActionPerformed

    private void jRadioButtonRelMPNpagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelMPNpagActionPerformed
        jRadioButtonRelMPAvarias.setSelected(false);
        jRadioButtonRelMPNumPerce.setSelected(false);
        jRadioButtonRelMPTotal.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelMPNpagActionPerformed

    private void jButtonRelMPGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelMPGerarActionPerformed

        String rel = "";

        String idMaq = jTextFieldRelMPIdMaq.getText();

            try {
                if (jRadioButtonRelMPNpag.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosMaqPagamento(1,idMaq);
                if (jRadioButtonRelMPTotal.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosMaqPagamento(2,idMaq );
                if (jRadioButtonRelMPNumPerce.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosMaqPagamento(3,idMaq );
                if (jRadioButtonRelMPAvarias.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosMaqPagamento(4,idMaq);
            } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }

        JOptionPane.showMessageDialog(null, rel, "Relatorio",1);
        System.out.println(rel);
         
}//GEN-LAST:event_jButtonRelMPGerarActionPerformed

    private void jTextFieldSelecDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSelecDiaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldSelecDiaActionPerformed

    private void jRadioButtonRelDiaViaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaViaturasActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaViaturasActionPerformed

    private void jRadioButtonRelDiaNBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaNBilheteActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaNBilheteActionPerformed

    private void jRadioButtonRelDiaTemposPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTemposPagActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaTemposPagActionPerformed

    private void jRadioButtonRelDiaEntEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaEntEstActionPerformed

        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaEntEstActionPerformed

    private void jRadioButtonRelDiaTempoEstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTempoEstaActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaTempoEstaActionPerformed

    private void jRadioButtonRelDiaOcupaNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaOcupaNivelActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaTotalEntSai.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaOcupaNivelActionPerformed

    private void jRadioButtonRelDiaTotalEntSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelDiaTotalEntSaiActionPerformed
        jRadioButtonRelDiaEntEst.setSelected(false);
        jRadioButtonRelDiaNBilhete.setSelected(false);
        jRadioButtonRelDiaOcupaNivel.setSelected(false);
        jRadioButtonRelDiaTempoEsta.setSelected(false);
        jRadioButtonRelDiaTemposPag.setSelected(false);
        jRadioButtonRelDiaViaturas.setSelected(false);
}//GEN-LAST:event_jRadioButtonRelDiaTotalEntSaiActionPerformed

    private void jButtonRelDiaGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelDiaGerarActionPerformed
        String rel = "";

        String dia_texto    = jTextFieldSelecDia.getText();
        String mes_texto    = jTextFieldSelecMes.getText();
        String ano_texto    = jTextFieldSelectAno.getText();
        int dia             = 0;
        int mes             = 0;
        int ano             = 0;
        int niveis          = 0;

        String msgErro      = "";

        // so aqui é que o dia, mes e ano fica com inteiro
        if (Util.isNumber(dia_texto)) dia = Integer.parseInt(dia_texto);
        if (Util.isNumber(mes_texto)) mes = Integer.parseInt(mes_texto);
        if (Util.isNumber(ano_texto)) ano = Integer.parseInt(ano_texto);

        // aqui verifica se o dia, mes e ano são válidos
        if (Util.isNumber(dia_texto) == false || dia > 31 || dia < 0)       msgErro = msgErro + "O dia inserido não é válido!\n";
        if (Util.isNumber(mes_texto) == false || mes > 12 || mes < 0)       msgErro = msgErro + "O mês inserido não é válido!\n";
        if (Util.isNumber(ano_texto) == false || ano < 2000 || ano > 2012)  msgErro = msgErro + "O ano inserido não é válido!\n";

        // mostra msg de erro se for caso disso, se estiver tudo bem gera o relatorio
        if (msgErro.equalsIgnoreCase("") == false) JOptionPane.showMessageDialog(null, msgErro, "Erro na data inserida!",1);
        else {
            try {
                niveis = niveis = Query.totalPisos();
                if (jRadioButtonRelDiaTotalEntSai.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(1, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaOcupaNivel.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(2, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaTempoEsta.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(3, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaEntEst.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(4, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaTemposPag.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(5, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaNBilhete.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(6, dia,mes,ano, niveis);
                if (jRadioButtonRelDiaViaturas.isSelected() == true) rel = GestaoRelatorios.gerarRelatoriosDiarios(7, dia,mes,ano, niveis);
            } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, rel, "Relatorio",1);
            System.out.println(rel);

        }
}//GEN-LAST:event_jButtonRelDiaGerarActionPerformed

    private void jButtonRelClienteGerarRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelClienteGerarRelActionPerformed
        String rel = "";
        String idCliente = jTextFieldidCliente.getText();

          try{
          if (jRadioButtonRelClienteNentrada.isSelected() == true)        rel = GestaoRelatorios.gerarRelatoriosCliente(1, idCliente);
          if (jRadioButtonRelClienteTemposEstacion.isSelected() == true)  rel = GestaoRelatorios.gerarRelatoriosCliente(2, idCliente);
          if (jRadioButtonRelClienteValorMensal.isSelected() == true)     rel = GestaoRelatorios.gerarRelatoriosCliente(3, idCliente);


        } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        JOptionPane.showMessageDialog(null, rel, "Relatorio",1);
        System.out.println(rel);
}//GEN-LAST:event_jButtonRelClienteGerarRelActionPerformed

    private void jTextFieldModoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModoEntradaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldModoEntradaActionPerformed

    private void jTextFieldidClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldidClienteActionPerformed

    private void jComboBoxTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoClienteActionPerformed
        String modo_texto = jComboBoxTipoCliente.getSelectedItem().toString();
        jListClientesRegistados.removeAll();
        ResultSet rSet;
        try {
            if(modo_texto.equals("Todos os Clientes")){
                DefaultListModel model = new DefaultListModel();
                if(jRadioButtonNCliente.isSelected()==true){
                    rSet = Query.queryClientes();
                    while (rSet.next()) {
                        model.addElement(rSet.getString(1));
                    }

                } else{

                    rSet = Query.queryClientes();
                    while (rSet.next()) {
                        model.addElement(rSet.getString(2));
                    }
                }
                jListClientesRegistados.setModel(model);
            } else{
                String modo;
                modo=Query.procuraModoEntradaPorNome(modo_texto);
                rSet = Query.filtraLista(modo);
                DefaultListModel model = new DefaultListModel();
                while(rSet.next()){
                    if(jRadioButtonNCliente.isSelected()==true){
                        model.addElement(rSet.getString(1));} else {
                        model.addElement(rSet.getString(2));
                        }

                }
                jListClientesRegistados.setModel(model);
            }


        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxTipoClienteActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (jTextFieldNomeCliente.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Seleccione o cliente que pretende alterar!", "Erro ao alterar cliente",1);
        } else {

            String idCliente = jTextFieldidCliente.getText();
            JDialogAlterCliente alterarProduto = null;
            try {
                alterarProduto = new JDialogAlterCliente(this, idCliente, true);
            }
       /* catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }*/
            catch (Exception ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }
            alterarProduto.setVisible(true);

        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonRegistarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarClienteActionPerformed
        JDialogNovoCliente adicionarCliente = new JDialogNovoCliente(this, true);
        adicionarCliente.setVisible(true);
}//GEN-LAST:event_jButtonRegistarClienteActionPerformed

    private void jRadioButtonNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeClienteActionPerformed
        jRadioButtonNomeCliente.setSelected(true);
        jRadioButtonNCliente.setSelected(false);
        jListClientesRegistados.removeAll();
        try {
            rSet = Query.queryClientes();
            DefaultListModel model = new DefaultListModel();
            while (rSet.next()) {
                model.addElement(rSet.getString(2));

            }
            jListClientesRegistados.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRadioButtonNomeClienteActionPerformed

    private void jRadioButtonNClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNClienteActionPerformed
        jRadioButtonNCliente.setSelected(true);
        jRadioButtonNomeCliente.setSelected(false);
        jListClientesRegistados.removeAll();
        try {
            rSet = Query.queryClientes();
            DefaultListModel model = new DefaultListModel();
            while (rSet.next()) {
                model.addElement(rSet.getString(1));

            }
            jListClientesRegistados.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jRadioButtonNClienteActionPerformed

    private void jButtonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarActionPerformed
        String sel = jTextFieldProcurar.getText();
        DefaultListModel model = new DefaultListModel();

        try {
            if (jRadioButtonNomeCliente.isSelected()) {
                rSet = Query.procuraClientePorNome(sel);
                while (rSet.next()) {
                    model.addElement(rSet.getString(2));
                }
                jListClientesRegistados.setModel(model);
            } else {
                rSet = Query.procuraClientePorID(sel);
                while (rSet.next()) {
                    model.addElement(rSet.getString(1));
                }
                jListClientesRegistados.setModel(model);
            }

        } catch (Exception ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButtonProcurarActionPerformed

    private void jTextFieldProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProcurarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldProcurarActionPerformed

    private void jListClientesRegistadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListClientesRegistadosValueChanged

        String sel = (String) jListClientesRegistados.getSelectedValue();

        try {

            if(jRadioButtonNCliente.isSelected()==true){
                rSet = Query.procuraClientePorID(sel);
            } else{
                rSet=Query.procuraClientePorNome(sel);
            }

            while (rSet.next()) {
                cliente.setIdCliente(rSet.getString(1));
                cliente.setNomeCliente(rSet.getString(2));
                cliente.setCodigoEntrada(rSet.getString(3));
                cliente.setMatricula(rSet.getString(4));
                cliente.setNib(rSet.getString(5));
            }


            jTextFieldidCliente.setText(cliente.getIdCliente());
            jTextFieldNomeCliente.setText(cliente.getNomeCliente());
            jTextFieldModoEntrada.setText(Query.procuraModoEntradaPorID(cliente.getCodigoEntrada()));
            jTextFieldMatricula.setText(cliente.getMatricula());
            jTextFieldNib.setText(cliente.getNib());

            DefaultListModel model = new DefaultListModel();
            String atraso = Query.pagamentoEmAtraso(cliente.getIdCliente());
            model.addElement(atraso);
            jListPagamentosAtrasoCliente.setModel(model);


        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListClientesRegistadosValueChanged

    private void jRadioButtonRelClienteNentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelClienteNentradaActionPerformed
         jRadioButtonRelClienteTemposEstacion.setSelected(false);
         jRadioButtonRelClienteValorMensal.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelClienteNentradaActionPerformed

    private void jRadioButtonRelClienteValorMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelClienteValorMensalActionPerformed
        jRadioButtonRelClienteTemposEstacion.setSelected(false);
         jRadioButtonRelClienteNentrada.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelClienteValorMensalActionPerformed

    private void jRadioButtonRelClienteTemposEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelClienteTemposEstacionActionPerformed
         jRadioButtonRelClienteValorMensal.setSelected(false);
         jRadioButtonRelClienteNentrada.setSelected(false);
    }//GEN-LAST:event_jRadioButtonRelClienteTemposEstacionActionPerformed

    private void jButtonRegistarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarPagamentoActionPerformed
        String idCliente = jTextFieldRegPagNCliente.getText();
        String modoPag = jComboBoxRegisPagForma.getSelectedItem().toString();
        String montante = jTextFieldRegPagMontante.getText();
        String data = jTextFieldRegisPagData.getText();
        
        String msgERRO = "";
            if (idCliente.equalsIgnoreCase(""))                     msgERRO = msgERRO + "Falta inserir o número do Cliente\n";
            if (modoPag.equalsIgnoreCase("Nao especificado"))       msgERRO = msgERRO + "Falta inserir o modo de pagamento\n";
            if (montante.equalsIgnoreCase(""))                      msgERRO = msgERRO + "Falta inserir o tempo do pagamento\n";
            if (data.equalsIgnoreCase(""))                          msgERRO = msgERRO + "Falta inserir a data do pagamento\n";

            System.out.println(msgERRO);

        if (msgERRO.equalsIgnoreCase("") == false) {
            JOptionPane.showMessageDialog(null, msgERRO, "Erro ao registar Pagamento", 1);
            }
        else {
            try {
                Query.adicionarPagamento(idCliente,data, modoPag,montante);
            } catch (SQLException ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
            }

                JOptionPane.showMessageDialog(null, "Pagamento registado com sucesso!", "Pagamento registado", 1);
                JInterfacePARKUM.this.dispose();

            }
        
    }//GEN-LAST:event_jButtonRegistarPagamentoActionPerformed

    private void jButtonRegistarPagamentomultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarPagamentomultaActionPerformed
            String id_bilhete = jTextFieldMultaBilhete.toString();
        try {
            BaseDados.registarPagamentoDeMulta(id_bilhete);
        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistarPagamentomultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            Model.connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new JInterfacePARKUM().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JInterfacePARKUM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonManRegista;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JButton jButtonRegistarCliente;
    private javax.swing.JButton jButtonRegistarPagamento;
    private javax.swing.JButton jButtonRegistarPagamentomulta;
    private javax.swing.JButton jButtonRelClienteGerarRel;
    private javax.swing.JButton jButtonRelDiaGerar;
    private javax.swing.JButton jButtonRelFacGerar;
    private javax.swing.JButton jButtonRelMPGerar;
    private javax.swing.JButton jButtonTabDistGera;
    private javax.swing.JComboBox jComboBoxRegisPagForma;
    private javax.swing.JComboBox jComboBoxTabDistHora;
    private javax.swing.JComboBox jComboBoxTabDistNivel;
    private javax.swing.JComboBox jComboBoxTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModoEntrada;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumerroCliente;
    private javax.swing.JLabel jLabelProcura1;
    private javax.swing.JLabel jLabelRelDia1;
    private javax.swing.JLabel jLabelRelFac1;
    private javax.swing.JLabel jLabelRelMP1;
    private javax.swing.JLabel jLabelRelMP2;
    private javax.swing.JLabel jLabelTabDist1;
    private javax.swing.JLabel jLabelTabDist2;
    private javax.swing.JList jListClientesRegistados;
    private javax.swing.JList jListPagamentosAtraso;
    private javax.swing.JList jListPagamentosAtrasoCliente;
    private javax.swing.JList jListTabelaDistribuicoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonNCliente;
    private javax.swing.JRadioButton jRadioButtonNomeCliente;
    private javax.swing.JRadioButton jRadioButtonRelClienteNentrada;
    private javax.swing.JRadioButton jRadioButtonRelClienteTemposEstacion;
    private javax.swing.JRadioButton jRadioButtonRelClienteValorMensal;
    private javax.swing.JRadioButton jRadioButtonRelDiaEntEst;
    private javax.swing.JRadioButton jRadioButtonRelDiaNBilhete;
    private javax.swing.JRadioButton jRadioButtonRelDiaOcupaNivel;
    private javax.swing.JRadioButton jRadioButtonRelDiaTempoEsta;
    private javax.swing.JRadioButton jRadioButtonRelDiaTemposPag;
    private javax.swing.JRadioButton jRadioButtonRelDiaTotalEntSai;
    private javax.swing.JRadioButton jRadioButtonRelDiaViaturas;
    private javax.swing.JRadioButton jRadioButtonRelFacPagCheque;
    private javax.swing.JRadioButton jRadioButtonRelFacPagDin;
    private javax.swing.JRadioButton jRadioButtonRelFacpagCartao;
    private javax.swing.JRadioButton jRadioButtonRelMPAvarias;
    private javax.swing.JRadioButton jRadioButtonRelMPNpag;
    private javax.swing.JRadioButton jRadioButtonRelMPNumPerce;
    private javax.swing.JRadioButton jRadioButtonRelMPTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldIDFuncionario;
    private javax.swing.JTextField jTextFieldManNumMaq;
    private javax.swing.JTextField jTextFieldManTempo;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModoEntrada;
    private javax.swing.JTextField jTextFieldMultaBilhete;
    private javax.swing.JTextField jTextFieldNib;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldProcurar;
    private javax.swing.JTextField jTextFieldRegPagMontante;
    private javax.swing.JTextField jTextFieldRegPagNCliente;
    private javax.swing.JTextField jTextFieldRegisPagData;
    private javax.swing.JTextField jTextFieldRelMPIdMaq;
    private javax.swing.JTextField jTextFieldSelecDia;
    private javax.swing.JTextField jTextFieldSelecMes;
    private javax.swing.JTextField jTextFieldSelectAno;
    private javax.swing.JTextField jTextFieldidCliente;
    private javax.swing.JTextPane jTextPaneManDescri;
    // End of variables declaration//GEN-END:variables

    public void update(Observable o, Object arg) {
        
    }
}
