-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO modos_entrada VALUES ('CA','Cartao de Avenca');

INSERT INTO modos_entrada VALUES ('RM','Reconhecimento de Matricula');

INSERT INTO modos_entrada VALUES ('VV','Via Verde');

INSERT INTO modos_entrada VALUES ('CW','Chamada Wireless');

