-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO pisos  VALUES ('1','50','0');

INSERT INTO pisos  VALUES ('2','50','0');

INSERT INTO pisos  VALUES ('3','50','0');

INSERT INTO pisos  VALUES ('4','50','0');

INSERT INTO pisos  VALUES ('5','50','0');

