-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO funcionarios  VALUES ('F01','Manuel','f01');

INSERT INTO funcionarios  VALUES ('F02','Fernando','f02');

INSERT INTO funcionarios  VALUES ('F03','Antonio','f03');

INSERT INTO funcionarios  VALUES ('F04','Jose','f04');

INSERT INTO funcionarios  VALUES ('F05','Paulo','f05');

INSERT INTO funcionarios  VALUES ('F06','Alcino','f06');

INSERT INTO funcionarios  VALUES ('F07','Alberto','f07');

INSERT INTO funcionarios  VALUES ('F08','Rui','f08');

INSERT INTO funcionarios  VALUES ('F09','Olga','f09');

INSERT INTO funcionarios  VALUES ('F10','Patricia','f10');
